### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by dacrypt** [jrquick17/ionic4-auto-complete#1]
There's a problem with dependencies:

```
ionic4-auto-complete@1.6.1 requires a peer of @angular/core@7.2.11
@angular/core@7.2.11 requires a peer of zone.js@~0.8.26
ionic4-auto-complete@1.6.1 requires a peer of zone.js@0.9.0
```

What to install to get it working?

**Comment by rmitache** [comment]
I have the same issue, did you manage to fix it ?

**Comment by jrquick17** [comment]
This is a warning from NPM about unmet dependencies that ionic4-autocomplete uses. This should not be a problem as long as you are using at least Angular 4. The peer dependencies have been removed in 1.7.4 to stop this message.
