### ISSUE TITLE
[Potential Bug] Missing selected item from the list after clicked on that item

### ISSUE THREAD

**Issue by bengchet** [jrquick17/ionic4-auto-complete#10]
Hi,

I met this weird issue when I was trying to access the list after I have clicked particular item. The item was missing from the list. If I clicked on another item, that another item is gone from list but the previous item is coming back. I have reproduce the item as below.

1. First, I open the menu, and there are 3 items shown. 
![Screenshot 2019-07-06 at 8 42 40 PM](https://user-images.githubusercontent.com/13192939/60756835-29697a00-a035-11e9-8fdd-c668d9e3faa0.png)

2. I typed admin and admin is shown as expected (I have added filter in data provider). Then clicked on it.
![Screenshot 2019-07-06 at 8 43 01 PM](https://user-images.githubusercontent.com/13192939/60756844-4c942980-a035-11e9-885a-0badae64d846.png)

3. When I try to delete the word slowly, the admin item doesn't show up in dropdown list.
![Screenshot 2019-07-06 at 8 50 34 PM](https://user-images.githubusercontent.com/13192939/60756857-7fd6b880-a035-11e9-8737-feb623e8ec6b.png)

4. After I deleted whole word, only 2 items left on the dropdown list.
![Screenshot 2019-07-06 at 8 50 46 PM](https://user-images.githubusercontent.com/13192939/60756874-bca2af80-a035-11e9-8768-5a7c5e6eef8d.png)

5. I clicked on the item (e.g. bengchet), and repeat step 3 and 4, and get as following. Item 'bengchet' is gone but 'admin' is back!
![Screenshot 2019-07-06 at 9 38 07 PM](https://user-images.githubusercontent.com/13192939/60756944-90d3f980-a036-11e9-8547-606cf7327c1e.png)

Have a time to look into it to check if it is bug or is it my configuration problem.  Please let me know if there is any update. Thanks.

*if I am using version 1.7.2, it is working.*
![Screenshot 2019-07-06 at 8 43 19 PM](https://user-images.githubusercontent.com/13192939/60756862-9715a600-a035-11e9-9f7b-4b4d6c6824c5.png)

**Comment by jrquick17** [comment]
Thank you for the help. This bug has been [fixed](https://github.com/jrquick17/ionic4-auto-complete/commit/6e8067bfc374372ebd825bf745a3102749de846d) and will be included in version `1.8.0`.
