### ISSUE TITLE
Question: can input-value ≠ auto-complete suggestions?

### ISSUE THREAD

**Issue by brunnurs** [jrquick17/ionic4-auto-complete#18]
Hi @jrquick17,

First of all many thanks for your work, especially fixing #11 that fast was very valuable to me!

My question: is it possible to fill the input with something different than the label which is displayed in the autocomplete list? Concretely I'm building a postcode/city autocomplete, and when the user is typing in the postcode he gets displayed suggestions based on a webservice. As soon as he clicks on one of the suggestions, the postcode input get's filled with the postcode and a second input for the city with the city name. _This is already working._

It would be nice though to not only display the postcode, but a combination of postcode & city in the autocomplete list. If he clicks on one though, the value filled in should be only the postal code (and the second input for the city get's filled via itemSelected()-event and the angular FormGroup).

I know that it's possible to define a different **formValueAttribute/labelAttribute**, but that's not really what I need. I would rather need a different label for the autocomplete-suggestions and what's really filled into the input.

Thanks for your help!

**Comment by jrquick17** [comment]
Hey @brunnurs! This should be possible using [ng-template for custom templates](https://github.com/jrquick17/ionic4-auto-complete/blob/master/README.md#custom-templates). When I have time I will try adding to the demo an example using custom templates, but no promise on timeframe.

**Comment by brunnurs** [comment]
Many Thanks, that works like a charm! My mistake, I should have read your manual more carefully...

In case anyone has the same requirements:
```html
<ng-template #postcodeCityTemplate let-attrs="attrs">
    <span [innerHTML]="(attrs.data.postcode | boldprefix:attrs.keyword) + ' (' + attrs.data.city + ')'"></span>
</ng-template>
```

**Comment by jrquick17** [comment]
For future reference, I have added an example using [custom templates to the demo](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/custom-template). 

[See Demo](https://ionic4-auto-complete.jrquick.com#custom-template)
