### ISSUE TITLE
dataProvider with basic Function

### ISSUE THREAD

**Issue by MarceloRGomes** [jrquick17/ionic4-auto-complete#19]
Hello,
I´m using Ionic v4 and Angular v8.
I´m using [dataProvider]="filter" , where filter is a function on same component.ts.
But, in this filter() I have a this.states where I want to filter items.
My state is public declared on top of this component.  But I always received a error message:

core.js:9110 ERROR TypeError: Cannot read property 'filter' of undefined
    at AutoCompleteComponent.filter [as dataProvider]

My filter function:

```
public filter(keyword) {
    keyword = keyword.toLowerCase();
    return this.states.filter(
      (object) => {
        return object.name.toLowerCase().indexOf(keyword) !== -1 
      }
    );
}
```
If I put a console.log(this.states), this variable is not recognized, but in all other functions, it works perfectly.  I don´t know what I can do...

**Comment by MarceloRGomes** [comment]
I tested using global var (I declared it before export class) and it works fine.  But I don´t like to use global vars. And this component doesn't run properly on <ion-col>

**Comment by aKaravanov** [comment]
I have the same issue.

**Comment by jrquick17** [comment]
Could either of you share a repo or stackblitz with the error? @MarceloRGomes @aKaravanov

**Comment by indrapalijama** [comment]
> Could either of you share a repo or stackblitz with the error? @MarceloRGomes @aKaravanov
> 
> Also, here is a [working demo](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/simple-function) using a function for reference.

hi! sorry for bothering you again, but it's 2021 and i still got the same issue as mentioned, and the working demo link is not working tho
