### ISSUE TITLE
Control is disabled and nothing happens

### ISSUE THREAD

**Issue by rmitache** [jrquick17/ionic4-auto-complete#2]
I've done everything like in the documentation, yet the control is disabled and nothing happens (not even any call to the getResults method in the autoCompleteService happens).

I am missing some peer dependencies, but am not sure if that is causing the problems.

Any help or thoughts would be most appreciated :) 

This is how it renders:
![ionic4-auto-complete](https://user-images.githubusercontent.com/20491406/57961496-a585f200-790f-11e9-9963-2f53c1161947.png)

**Comment by bashoogzaad** [comment]
I have the same issue, there was a commit in which isInitializing is introduced. Now the autocomplete input wants on a value, I dont understand why. Maybe someone knows why this commit was made?

**Comment by callegri** [comment]
I have the same issue with isInitializing property...

**Comment by israelvitor97** [comment]
I have the same issue

**Comment by israelvitor97** [comment]
See the ionic demo folder in the repository. It's different from the documentation. It works.

**Comment by jrquick17** [comment]
`isInitializing` has been removed. It was originally added to keep the input disabled until data is loaded  but since this is not a use case for everyone it has been removed. Instead `disabled` will have to be manually set until the model is loaded. 

This issue has been fixed in `1.7.4`.
