### ISSUE TITLE
Pass other data into autocomplete

### ISSUE THREAD

**Issue by WildSunLove** [jrquick17/ionic4-auto-complete#24]
Aloha, this is really just a question, so apologies if I'm not submitting this in the right style. I can change it to a feature request in the proper style if that's what it ends up being.

My question in this space is I am trying to figure out if it is possible to pass other data into the autocomplete besides just the keyword.

The example in this case is that I have an autocomplete to search for people, but there is a selector next to the autocomplete that is either for "global" or "sphere", to basically pass to the backend to tell it to search for people from the whole world, or from my inner sphere of friends. So I am wondering how I might go about passing this bit of information into my autocomplete service so that it can pass it to the database.

Thanks much! :)

**Comment by WildSunLove** [comment]
This can actually totally be done by just using a function as dataProvider rather than a service. Closing this. :)

**Comment by airasyaqub** [comment]
Can you please provide the solution for how u did it.

**Comment by WildSunLove** [comment]
I spoke too soon upon closing this, as I quickly discovered there does not seem to be a way to apply labelAttribute when using a function as the provider, which also seems necessary.

Continuing to explore this, and specifically how to pass other filter options to the getResults query beyond simply the keyword.

**Comment by jrquick17** [comment]
Could you use custom ngTemplates instead of the `labelAttribute`?

**Comment by WildSunLove** [comment]
Is this documented somewhere? I'm not too experienced with ngTemplates

**Comment by WildSunLove** [comment]
That sounds like the ideal way to do it, as I want to be able to show a users avatar in the autocomplete as well as their name. Just hadn't seen how that was done.

**Comment by jrquick17** [comment]
Sure here is an example, let me know if you have problems. 

https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/custom-template

**Comment by WildSunLove** [comment]
Oh wow that is absolutely perfect, thanks so much :)

**Comment by WildSunLove** [comment]
Ah ok and now the other question
Is there an effective way to access instance variables inside of a filter that is being passed as provider. Some things happen with the context, so it doesn't seem to have the usual access to instance variables

**Comment by jrquick17** [comment]
Could you give me an example of what you're trying to accomplish?

**Comment by WildSunLove** [comment]
Here's the function

```
filterPeople(keyword: string) {
    if (this.sphere == 1) {
      return this.peopleServ.getPeople({ friends_only: true, nameq: keyword });
    } else {
      return this.peopleServ.getPeople({ nameq: keyword });
    }
  }
```

And it throws the error that it cannot read property getPeople of undefined. So basically the instance variable peopleServ, which is defined in the constructor, is not accessible here.

**Comment by WildSunLove** [comment]
I solved this by defining the function like;
`filterPeople = (keyword: string) => { ... }`

Something with how context works in Javascript that I only partially understand lol
