### ISSUE TITLE
Data provider service with multiple parameters

### ISSUE THREAD

**Issue by airasyaqub** [jrquick17/ionic4-auto-complete#25]
I have an API that needs multiple params to work. The "getResults(keyword:string)" method of AutoComplete interface only takes the keyword which is typed in the search bar. How can I send multiple params to the package method?

**Comment by jrquick17** [comment]
So you want to search for a single object using multiple fields?   

For example: Search for a book based on title and author?

**Comment by airasyaqub** [comment]
Basically I have an API that takes two parameters to search for a place, city and search keyword. I cant understand the way to send the city param to data provider service.

**Comment by jrquick17** [comment]
Checkout [the demo code](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo) for help. Both the simple function and simple provider examples can achieve this.
