### ISSUE TITLE
(itemChanged) and (itemRemoved) not firing

### ISSUE THREAD

**Issue by WildSunLove** [jrquick17/ionic4-auto-complete#26]
I've got a fairly standard ion-auto-complete component, and (itemSelected) seems to fire regularly but nothing I am doing is getting (itemChanged) or (itemRemoved) to fire. I would expect both of these to fire when the X is clicked to cancel out data, and expect (itemChanged) to fire like (itemSelected) when an item is selected, but (itemSelected) is the only one firing

**Comment by jrquick17** [comment]
Could you check [the demo](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo)? I have added console logs for each event so that it can be easily tested. Both events appear to be firing. If they are not for you then please include reproduction steps.

**Comment by jchalare** [comment]
Same issue, how did you solved ?
