### ISSUE TITLE
Assets are not being copied into the build/package

### ISSUE THREAD

**Issue by sanaadostmuhammad** [jrquick17/ionic4-auto-complete#27]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

The assets folder is not being copied into the the final build/package. The issue can be fixed by updating the build command to    "build": "ng-packagr -p package.json && cp src/scss/auto-complete.scss dist/auto-complete.scss  && cp -r src/assets dist/assets",

### Version Information

```
"version": "2.1.4"
```

### Browser

- [x] Chrome - Version 77.0.3865.90
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by jrquick17** [comment]
This has been fixed [in v2.2.0](https://github.com/jrquick17/ionic4-auto-complete/commit/1f20c81beb86f7d730f333460dfa604db053e350). Thank you!
