### ISSUE TITLE
[BUG]: Doesn't work inside of an ion-item

### ISSUE THREAD

**Issue by brenden-t-r** [jrquick17/ionic4-auto-complete#28]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

- [ ] Bug: When component is put inside of an ion-item, the filtered results are not displayed

### Version Information

```
angular: 7
```

### Browser

- [ z] Chrome -  77.0.3865.120

**Comment by WildSunLove** [comment]
Yep have noticed this as well. I just took it out of `ion-item` and haven't run into issues but suppose there are instances where it would be quite inconvenient to do so

**Comment by brenden-t-r** [comment]
My hack was to use an ion-row with custom css to make it appear as the rest of the ion items

**Comment by jrquick17** [comment]
Add `overflow` to `ion-item`. Must be a style, not class because of how Shadow DOM works.

Example:
```
<ion-item style="overflow: visible;">
   <ion-auto-complete ...></ion-auto-complete>
</ion-item>
```

**Comment by jrquick17** [comment]
Example 2:
https://github.com/jrquick17/ionic4-auto-complete/commit/dff0cf9783ed39675abcd7b29a8e9d9d05208c19
