### ISSUE TITLE
[BUG]: Selected items disappear from the list

### ISSUE THREAD

**Issue by GuilleOH** [jrquick17/ionic4-auto-complete#29]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

- [x ] Bug: When I select an item from the list, I delete the input and then filter again, I cannot see the previously chosen item
![Screenshot_2019-10-17 Ionic App](https://user-images.githubusercontent.com/29570952/67000774-b9a96780-f0d8-11e9-866f-797e9f806060.png)
![Screenshot_2019-10-17 Ionic App(1)](https://user-images.githubusercontent.com/29570952/67000819-cc23a100-f0d8-11e9-94fa-c1691cafa3fc.png)
![Screenshot_2019-10-17 Ionic App(2)](https://user-images.githubusercontent.com/29570952/67000864-dcd41700-f0d8-11e9-96b8-c283cdc2cb91.png)

### Version Information

ionic4-auto-complete": "^1.9.0"
angular: 7.2.2

### Browser

- [ x] Mozilla Firefox - 69.0.2

**Comment by Dipan61241828** [comment]
Just remove the line from index.js of library in setSuggestions function 
**suggestions = this.removeDuplicates(suggestions);**

it will display your selected item also.

**Comment by GuilleOH** [comment]
> Just remove the line from index.js of library in setSuggestions function
> **suggestions = this.removeDuplicates(suggestions);**
> 
> it will display your selected item also.

Thanks! It worked

**Comment by jrquick17** [comment]
This is fixed in v2.2.1
