### ISSUE TITLE
How to clear input 

### ISSUE THREAD

**Issue by alejuanito** [jrquick17/ionic4-auto-complete#3]
Hi, how to clear the input auto-complete after search data?

**Comment by jrquick17** [comment]
If `multi` is set `true` then the input will be cleared once an item is selected. If `multi` is set to `false` then the input can be cleared by clicking the X on the right side of the text input.

There are plans to add a [clear button to multi inputs](https://github.com/jrquick17/ionic4-auto-complete/projects/1#card-22985523) and to [multi selected items](https://github.com/jrquick17/ionic4-auto-complete/projects/1#card-22985513).
