### ISSUE TITLE
[Feature]: Add results limit

### ISSUE THREAD

**Issue by jorisbertomeu** [jrquick17/ionic4-auto-complete#30]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description

- [ ] Bug: Description of the issue you encountered_
- [X] Feature: Add an option "resultsLimit" in order to show only *resultsLimit* results

**Comment by jrquick17** [comment]
This has been [added in v2.2.0](https://github.com/jrquick17/ionic4-auto-complete/commit/e854a41643ccdb800a5c5ef054f8f66eab63a11c).
