### ISSUE TITLE
Call for clearing input?

### ISSUE THREAD

**Issue by WildSunLove** [jrquick17/ionic4-auto-complete#32]
Is there a callback for when you click the button to clear the input field?

Been looking but unable to find.

**Comment by jrquick17** [comment]
There is not one specifically for when the user presses the clear button. However, there is `itemRemoved`. 

If you submit a pull request I'll gladly merge it, otherwise I will add this feature when I have more time.

**Comment by jrquick17** [comment]
This has been added in [this commit](https://github.com/jrquick17/ionic4-auto-complete/commit/93ffa4641aae6238eb5ec061ca6e21a3ac3b59dd) and will be released in v2.4.0
