### ISSUE TITLE
[BUG]: Use as ion-input throws TypeError: "event.detail.target is undefined" on keyboard input

### ISSUE THREAD

**Issue by Birdstown** [jrquick17/ionic4-auto-complete#34]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description
When using the component as an ion-input (useIonInput="true") keyboard input throws the following error:

Firefox - TypeError: "event.detail.target is undefined"
Chrome - ERROR TypeError: Cannot read property 'value' of undefined
Edge - ERROR TypeError: Unable to get property 'value' of undefined or null reference

After a bit of digging, it appears that the ion-input relies on a ```keyup``` event that does not have the ```detail.target.value``` property required in ```getItems(event, show)``` - the searchbar on the other hand uses an ```ionInput``` event that does have this property.

### Browser

- [X] Chrome - 78.0.3904.108
- [X] Mozilla Firefox - 70.0.1
- [X] Microsoft Edge - 44.18362.449.0

**Comment by jrquick17** [comment]
[Fixed in v2.4.1](https://github.com/jrquick17/ionic4-auto-complete/commit/94c7a4100f01368c8ca92148881e046c6c1b0550)
