### ISSUE TITLE
[BUG]: Can't set value to input by  [(ngModel)]

### ISSUE THREAD

**Issue by mrmikez** [jrquick17/ionic4-auto-complete#37]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

- [x] Bug: Description of the issue you encountered_
- [ ] Feature: Description of the feature. Cause and its Motivation_

### Version Information

```
Angular: 8.1.3
Ionic : 5.4.9
```

### Browser

- [x] Chrome - 78.0.3904.108 
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

I have something like this in my html:
```

<form (ngSubmit)="add()" class="form" name="MyForm">

    <ion-auto-complete name="nameinput"
                       [ngClass]="Condition() ?'A':'B'"
                       [dataProvider]="dataProviderService"
                       [(ngModel)]="variableToSet"
                       [options]="{clearInput:false, clearOnEdit:false,clearInvalidInput:false}"
                       (itemSelected)="callWhenSelected()"
                       (ionAutoInput)="userInput()"
                       [clearInvalidInput]="false"

    >
    </ion-auto-complete>
<ion-button (click)="test()">Use current location</ion-button>
  </form>
```

The method test() sets some text to variable, but there is no change in autocomplete input. 
I have three types of input for autocomplete input box : 

1. selected item from list provided by your module
2. user input validated by some regex, I am geting user input by   (ionAutoInput)="userInput()" - it comes as atributte $event. This is maybe not best practice, but it works for me (- variableToSet is set after selecting item from list.) 
3. is the test() method - it sets some string to variableToSet - but code above not works for me - noting is set to autocomplete box, what i am doing wrong? can you help me please? It looks similar as https://github.com/jrquick17/ionic4-auto-complete/issues/18 but how i can use it ? Imports for Forms are correct, [(ngModel)] works for other inputs from this form.

**Comment by jrquick17** [comment]
So help me understand. 

You are updating the variable `variableToSet` when the user clicks the button which fires `test()` and the new value is not reflected in the auto complete?

**Comment by mrmikez** [comment]
> So help me understand.
> 
> You are updating the variable `variableToSet` when the user clicks the button which fires `test()` and the new value is not reflected in the auto complete?

Yes, exactly.

**Comment by jrquick17** [comment]
@mrmikez 

This appears to be working for me. [I added an example to test this exact scenario here. ](https://github.com/jrquick17/ionic4-auto-complete/commit/8d8972bc984a597d805dced9a67ef9d73aa0f7ab)

Feel free to reopen if I missed something.
