### ISSUE TITLE
Getting Error when trying to create apk out of this component

### ISSUE THREAD

**Issue by csplrj** [jrquick17/ionic4-auto-complete#38]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description
Bug
I am getting below error when I run "ionic cordova build android --prod --release"?
So It seems something is missing in the plugin.

ERROR in ./node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\mybizapp-ionic\node_modules\ionic4-auto-complete\auto-complete\auto-complete.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\mybizapp-ionic\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (C:\mybizapp-ionic\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/app/createenquiry/createenquiry.page.ngfactory.js
Module not found: Error: Can't resolve '../../../node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.ngfactory' in 'C:\mybizapp-ionic\src\app\createenquiry'
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build:production --platform=android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

### Version Information
Ionic 4.1
Ionic Autocomplete 1.9.0
```
### Browser

IONIC CLI

**Comment by jrquick17** [comment]
@csplrj 

This issue is because in your angular.json file you need to change `@ionic/ng-toolkit` into `@ionic/angular-toolkit`.

[See this issue.](https://github.com/ionic-team/ionic-cli/issues/3763)

**Comment by developermw** [comment]
Same error with @ionic/angular-toolkit also

**Comment by viruzck** [comment]
Hi i have a same error with @ionic/angular-toolkit also

Ionic Autocomplete 1.9.0

Ionic info:
```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : browser 6.0.0, ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.3, (and 13 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v8.15.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 11.3 Build version 11C29
```
