### ISSUE TITLE
Observable errors should be logged

### ISSUE THREAD

**Issue by rsivan** [jrquick17/ionic4-auto-complete#46]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

- [x] Bug: Description of the issue you encountered_
- [ ] Feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ionic4-auto-complete: x.x.x
@angular/cli: x.x.x
```

### Browser

- [ ] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by rsivan** [comment]
I was investigating an empty results list when I realized there was an error in the values returned by an Observable.
Unfortunately the component does not log the error anywhere.
I would recommend the subscription handler include error handling and logging of the error.

To diagnose the problem I subscribed my own code and found that there was an error in the service I was querying as part of the autocomplete.

Thanks

**Comment by jrquick17** [comment]
Hey @rsivan, I am not 100% sure that I am following. Are you saying you think I should catch the error and throw another? Like so:

```
    search(): Observable<user[]> {
        return this.http.get().pipe(catchError(this.errorHandler));
    }

    errorHandler(error: HttpErrorResponse) {
        return Observable.throw(error.message || "Error caught from service provider.");
    }
```

**Comment by rsivan** [comment]
You are right, I just noticed the code does handle errors.
Not sure why I don't see them unless I start a parallel http request and subscription...
I was debugging on Android using Android Studio.

BTW I pulled 2.5.0 from npm but there is no tag for it on github.

Thanks.

**Comment by rsivan** [comment]
In other words this code seems to handle them as I was suggesting:
`            ).subscribe(
                (results: any[]) => {
                  this.setSuggestions(results, show);
                },
                (error: any) => console.error(error)
`

**Comment by jrquick17** [comment]
Thank you. I will add a tag.

**Comment by rsivan** [comment]
Just another observation: I added a catchError pipe in my code.
The code displays an error to the console and then rethrows it:
```
  ...pipe(
     catchError(err => {
       console.error('Error searching term: ', JSON.stringify(err));
       return throwError(err);
     }),
```
Now when I throw an error on Chrome, I see both the error I display and the one displayed from the AutoComplete plugin.
However when running under Android only my own code is displayed.
Any thoughts?

Thanks.

**Comment by jrquick17** [comment]
That is interesting. 

My best guess would be Cordova or Ionic are automatically removing console logs from dependencies. If so, I wander if building without the prod flag or using the debug apk would show both console logs.
