### ISSUE TITLE
[BUG] ionic5 emptyTemplate and selectionTemplate not working

### ISSUE THREAD

**Issue by moneycoach2019** [jrquick17/ionic4-auto-complete#47]
> Hey @moneycoach2019, can you share an example of `emptyTemplate` and/or `selectionTemplate` not working? It is working in the custom template [demo](https://ionic4-auto-complete.jrquick.com/#custom-template), code [here](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/custom-template).
> 
> _Originally posted by @jrquick17 in https://github.com/jrquick17/ionic4-auto-complete/issues/44#issuecomment-577300083_

As stated in the previous bug report where you fixed the time delay problem, in ionic5 the regular template works, but empty or selectionTemplate wont.

Here the examples for `emptyTemplate`:

```
  <ng-template #empty let-attrs="attrs">
    <ion-text class="ion-text-right ion-padding-vertical">That country does not exist!</ion-text>
  </ng-template>

          <ion-auto-complete [(model)]="cryptoFrom" [dataProvider]="cryptoPairProvider" [template]="withSymbols" [emptyTemplate]="empty" [options]="{ placeholder : 'From:', debounce: 1 }" style="width:100%"></ion-auto-complete>
```

**Comment by jrquick17** [comment]
This is [fixed](https://github.com/jrquick17/ionic4-auto-complete/commit/4ce627852c84e5c00d664f0b76390f4756698239) in v2.5.2.

The empty template was not displaying only when the autocomplete options did not have `noItems` set.
