### ISSUE TITLE
[BUG]: Empty value with multi property

### ISSUE THREAD

**Issue by GregoryMerlet** [jrquick17/ionic4-auto-complete#49]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When you use the return key on the component with the `multi` property set to true, an `undefined` value is added to the selected values and it's displayed as an empty value.

![Capture](https://user-images.githubusercontent.com/3045716/73168286-d6066880-40f9-11ea-8962-65d2379115d4.PNG)

You can reproduce it on the demo version here : 
https://ionic4-auto-complete.jrquick.com/#multi-function

### Version Information

```
ionic4-auto-complete: 2.5.1
@angular/cli: 8.3.21
```

### Browser

- [x] Chrome - 79.0.3945.130
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by jrquick17** [comment]
This has been [fixed](https://github.com/jrquick17/ionic4-auto-complete/commit/e02b8fe5cf138bba33768e263edae833bcb29cb4) and will be released in v2.5.2.
