### ISSUE TITLE
[BUG] Default for options.debounce gets not set

### ISSUE THREAD

**Issue by mgreg89** [jrquick17/ionic4-auto-complete#50]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

- [x] Bug: Description of the issue you encountered_
- [ ] Feature: Description of the feature. Cause and its Motivation_

If options.debounce is not set by the user, the following line calls setTimeout with undefined, since the default value for debounce is not assigned: https://github.com/jrquick17/ionic4-auto-complete/blob/244c2c55d61fcda153261574b265e52485722f7f/src/auto-complete/auto-complete.component.ts#L393
This results in getting the search keyword in data provider's getResults call from the previous input event.
If debounce is explicitly set by the user, the behavior is as expected: After debounce ms getResult is called with the current keyword.

### Version Information

```
ionic4-auto-complete: 2.5.1
@angular/cli: 8.3.20
```

### Browser

- [ ] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x
- [x] Android Webview
<br>

**Comment by jrquick17** [comment]
This issue has been [fixed](https://github.com/jrquick17/ionic4-auto-complete/commit/6b3dda20b6bc538e0623c59938aae96f893d7c9b) and will be released in v2.5.3.

**Comment by mgreg89** [comment]
Unfortunately, with version 2.6.0 this bug still exists. Still getResults is getting the keyword from the input event which happened before the last typed letter. So, if I type "Abcd" getResult is called with "Abc". If I happen to type another "e", then getResult is fired with "Abcd".
I think, options.debounce is still undefined, if it doesn't get explicitly set by the developer (not instantiated with default value).
