### ISSUE TITLE
[Feature]: Option to add the input when no items match the input

### ISSUE THREAD

**Issue by AKwoKWH** [jrquick17/ionic4-auto-complete#51]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

- [ ] Bug: Description of the issue you encountered_
- [x] Feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ionic4-auto-complete: x.x.x
@angular/cli: x.x.x
```

### Browser

- [x] Chrome - x.x.x
- [x] Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by Mantaras96** [comment]
Hello any news about this?

**Comment by jrquick17** [comment]
I don't have the time to add this feature at the moment. Feel free to submit a pull request and I will create a new release.

**Comment by jrquick17** [comment]
This is already possible with the current version using the custom template feature. I have [added an example](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/ingredient-picker) to [the demo](https://ionic4-auto-complete.jrquick.com/#ingredients).
