### ISSUE TITLE
Two Input fields are shown and works together

### ISSUE THREAD

**Issue by JeongJun-Lee** [jrquick17/ionic4-auto-complete#52]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description
![image](https://user-images.githubusercontent.com/11474775/73750900-dbaa2100-477f-11ea-91ef-96ea72fcaad8.png)

Two Input fields are shown and when I typed some words in one of them, the word are shown in both input fields at the same time.

How can I remove the upper input filed?

Example:
https://stackblitz.com/edit/ionic-4-angular-8-start-template-l5as1d?file=src%2Fapp%2Ftab3%2Ftab3.page.html

- [x] Bug: Description of the issue you encountered_
- [ ] Feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ionic4-auto-complete: 2.5.2
@angular/cli: 8.1.2
```

### Browser

- [x] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by Birdstown** [comment]
You need to import the scss for the component into your app.scss/global.scss - see https://github.com/jrquick17/ionic4-auto-complete#add-styles. 

Leaving this out causes the visibility of both fields, as well as the bullets you're reporting in #53

**Comment by JeongJun-Lee** [comment]
Thanks.  I applied it to app.scss. Another issue comes out. Like below, 
![image](https://user-images.githubusercontent.com/11474775/73839899-d957cd80-4838-11ea-9887-a44b1650acc2.png)
the loading image will show forever without showing suggestions.

**Comment by JeongJun-Lee** [comment]
Right. It's my mistake. I have to apply the scss like https://github.com/jrquick17/ionic4-auto-complete#add-styles. I'll close this. https://github.com/jrquick17/ionic4-auto-complete/issues/52#issuecomment-582375182 is still. I'll open new issue about it. Thanks.

**Comment by JeongJun-Lee** [comment]
https://github.com/jrquick17/ionic4-auto-complete/issues/52#issuecomment-582375182 the 
 root cause is not to return complete method from Firestore database. To solve this, you can use take(1) pipe.
