### ISSUE TITLE
[Feature]: Add scrollbar to suggestions list

### ISSUE THREAD

**Issue by JeongJun-Lee** [jrquick17/ionic4-auto-complete#54]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description
![image](https://user-images.githubusercontent.com/11474775/73777581-8dab1280-47ab-11ea-87da-eb404e15b075.png)

Actually there are 12 matches but it shows 7 matches by ion-item in ion-list. I think the scrollbar should be supported to show 5 matches more because I used ion-list.

Example:
https://stackblitz.com/edit/ionic-4-angular-8-start-template-l5as1d?file=src%2Fapp%2Ftab3%2Ftab3.page.html

- [ ] Bug: Description of the issue you encountered_
- [x] Feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ionic4-auto-complete: 2.5.2
@angular/cli: 8.1.2
```

### Browser

- [x] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by jrquick17** [comment]
@JeongJun-Lee You should be able to pass css styling through the `[styles]` attribute to achieve the desired affect by setting height and overflow attributes on the list element.

**Comment by JeongJun-Lee** [comment]
@jrquick17 Thanks. I appied [styles]="{list: {overflow: 'scroll', height: '200px'}}". But still when I press 'a', even though totally there are all 12 matches, it shows only 8 matches with scrollbar.

**Comment by JeongJun-Lee** [comment]
OK I found how to do it. I need to set the attribute like [maxResults]="1000"
