### ISSUE TITLE
[Feature]: Multi-field example?

### ISSUE THREAD

**Issue by gaharrington** [jrquick17/ionic4-auto-complete#57]
# I'm submitting a
- [X] Documentation issue or request

## Description

Is it possible to show two fields in the results with different formatting? 
e.g. Google Maps shows the location title and the address with different formatting: https://share.getcloudapp.com/BluBggJg

### Version Information

```
    "ionic4-auto-complete": "^1.10.0",
    "@angular/cli": "~7.3.8",
```

**Comment by jrquick17** [comment]
You would have to use the custom templates to make that work. Something like this:

```
<ng-template #suggestions
                         let-attrs="attrs">
        <div class="attrs.data.format_class">
            {{ attrs.data.display_format }}
        </div>
</ng-template>
```

Checkout the custom tempate [demo](https://ionic4-auto-complete.jrquick.com/#custom-template) and the [code](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/custom-template) for more details.
