### ISSUE TITLE
[Documentation]: How to: Results attribute different from chosen item displayed attribute?

### ISSUE THREAD

**Issue by gaharrington** [jrquick17/ionic4-auto-complete#58]
# I'm submitting a
- [X] Documentation issue or request

## Description

Can I show one attribute in the results (e.g. "first_name") and a differrent one in the chosen item that is displayed (e.g. "full_name")

In the demo, I see the following code (but it seems to control both):
`export class SimpleFunction implements AutoCompleteService {
    labelAttribute = 'full_name';
`
### Version Information

```
    "ionic4-auto-complete": "^1.10.0",
    "@angular/cli": "~7.3.8",
```

**Comment by jrquick17** [comment]
You could set the `labelAttribute` equal to `first_name` (or whatever you want to search) and then use the custom template feature to change what is shown in your selection: 

```
<ng-template #selection
             let-attrs="attrs">
        {{ attrs.data.full_name }}
</ng-template>
```

Checkout the custom tempate [demo](https://ionic4-auto-complete.jrquick.com/#custom-template) and the [code](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/custom-template) for more details.
