### ISSUE TITLE
Double textbox showing

### ISSUE THREAD

**Issue by jitendrag645** [jrquick17/ionic4-auto-complete#63]
# I'm submitting a
showing double textbox when served

## Description
![Capture](https://user-images.githubusercontent.com/35837219/77219837-8e331900-6b5f-11ea-8715-ac30db141871.PNG)

**Comment by jrquick17** [comment]
@jitendrag645 I am closing this. Try upgrading to the latest version and be sure to add the scss file to your package. If that does not work then feel free to open another issue but please share a reproducible example.
