### ISSUE TITLE
[BUG] problem with labelAttribute

### ISSUE THREAD

**Issue by mecherguiAhmed** [jrquick17/ionic4-auto-complete#64]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

- [x] Bug: Description of the issue you encountered_
- [ ] Feature: Description of the feature. Cause and its Motivation_

Hi,

I'm facing an issue with   "labelAttribute", "formValueAttribute".
When i specify the "labelAttribute" only, the process works as expected : the displayed label and the form value are the same.
but the problem is when i add a "formValueAttribute", it looks like it ignores the label attribute and displays the formValueAttribute in the suggestions.

Example:
for: 
labelAttribute = name; 
suggestion: name, value: name

for: 
labelAttribute = name; 
formValueAttribute = numericCode;
suggestion: numericCode, value: numericCode

### Version Information

```
ionic4-auto-complete: ^1.10.1
@angular/cli: ~8.2.14
@ionic/angular: ^5.0.0
```

### Browser

- [x] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by jrquick17** [comment]
@mecherguiAhmed  I am closing this. Try upgrading to the latest version and be sure to add the scss file to your package. If that does not work then feel free to open another issue but please share a reproducible example.
