### ISSUE TITLE
(itemChanged) and (itemRemoved) not firing 

### ISSUE THREAD

**Issue by jchalare** [jrquick17/ionic4-auto-complete#67]
Hello, I have this in my HTML: 
 <ion-auto-complete [dataProvider]="someService"  
                                (itemSelected)="SelectedMethod($event)"
                                (itemRemoved)= "cleanSelected($event)" >
</ion-auto-complete>

and the method itemRemoved is not working, only works itemSelected. please help, how can i solve this issue.

**Comment by jrquick17** [comment]
Check the demo for an example. It has an `on()` function in each one which writes to the console when fired. 

[Code Here](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/team-picker)

[Demo Here]

**Comment by jchalare** [comment]
This is my service: 
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { map } from 'rxjs/operators';
import { Observable, of } from 'rxjs';
import { AutoCompleteService } from 'ionic4-auto-complete';
import { ConexionApiService } from '../services/conexion-api.service';
import { environment } from 'src/environments/environment';
import { UiServiceService } from 'src/app/services/ui-service.service';
const URL = environment.url;

@Injectable({
  providedIn: 'root'
})
export class ServicioPlacaService implements AutoCompleteService {
  labelAttribute = 'codigo_vehiculo';
  formValueAttribute = 'placa';
  public placas: any[] = [];
  public idVehiculo;

  constructor(private http: HttpClient, private conexion: ConexionApiService, private uiService: UiServiceService ) {

  }
 
 getResults(keyword: string) {
    if (!keyword) { 
      return false; 
    }else{
      const headers = new HttpHeaders({
        token: this.conexion.tokenData,
        "Content-Type": "application/json"
      });

      const urlCompleta = URL + `?view=vehiculo/${keyword}`;

      return this.http.get(urlCompleta, { headers }).pipe(map(
        (result: any[]) => {   
          const codigoDato = result['code'];

          if (codigoDato) {
            const arregloDatos = result['data'];

            if (typeof (arregloDatos) !== 'string') {
              this.uiService.mostrarLoading();
              return arregloDatos.filter(
                (item) => {
                  return item.placa.toLowerCase().startsWith(
                    keyword.toLowerCase()
                  );
                }
              );
            } else {
              this.uiService.mensajeToast('Placa NO es válida', 'danger');
            }
          }
        }
      ));
    }
  }

  getItemLabel(vehiculo: any) {
    this.idVehiculo = vehiculo.codigo_vehiculo;
    return vehiculo.placa;
  }

}
/////////////////////////////////////////////////////////////////////////////////////////////
This is my .ts: 

buscarPlaca( event ) {
   const idPlaca = event.codigo_vehiculo;
   if (idPlaca) {
      this.okPlaca = 'bien';
      this.grabarAlistamiento.vhcid = idPlaca;
  } 
}

 limpiar(event) {
   console.log(event);
  }

/////////////////////////////////////////////////////////////////
 and finally this is the html file:
<ion-auto-complete [dataProvider]="servicioPlaca" 
                                   (itemSelected)="buscarPlaca($event)"
                                   (itemRemoved)= "limpiar($event)"
                                   [(ngModel)]="alistamiento.placa"  name="placa" id="placa"
                                   [options]="{ placeholder : 'Digite una Placa',
                                                 debounce:1500,
                                                 color:'light' }" ></ion-auto-complete>

I tried the demo and it worked well, but in my code, i just dont know what else to do. any help i really apreciate that

**Comment by jrquick17** [comment]
Hey @jchalare, it is hard to tell without runnning the code. From what you provided, I do not see the problem. If you can create a small code sample the reproduces the error which I could run then I would have a better chance of finding the issue. You could create a GitHub repo or just share a StackBlitz.
