### ISSUE TITLE
I can't catch the selected item from the list on itemSelected Event.

### ISSUE THREAD

**Issue by phyzerbert** [jrquick17/ionic4-auto-complete#68]
I have tried to catch the selected item from the list.
This is my html and ts code.
<ion-auto-complete
                #searchbar
                [(model)]="selected"
                [multi]="false"
                [dataProvider]="provider"
                [disabled]="false"
                [maxResults]="100"
                [removeButtonColor]="'dark'"
                [autoFocusSuggestion] = "false"
                [options]="options"
                (itemSelected)="strainSelected($event)"
                (autoBlur)="strainSelected($event)"
></ion-auto-complete>

**** .ts ******
strainSelected(event: any) {
    console.log(event);
    if(event.id){
      this.router.navigate(['/strain/show', event.id]);
    }    
}

if i click the first top item, it shows this.
![image](https://user-images.githubusercontent.com/46837938/83364712-30804000-a3de-11ea-9cbe-6ff2f400044b.png)

and i click again, i can get the selected item.
How can i get the selected item from the first click?
![image](https://user-images.githubusercontent.com/46837938/83364730-602f4800-a3de-11ea-892c-af783c1cd8a9.png)

**Comment by jrquick17** [comment]
`(ionBlur)` does not return the selected item, it returns an CustomEvent object. 

Instead, you can get the item recently added using `(itemSelected)` or you can use `(itemsChange)` to get all of the selected items after something is added or removed.

The ionBlur event is firing before the itemSelected event (should be reversed) which may explain why your having issues. Basically, try removing (ionBlur). 

If that does not work feel free to reopen this issue. And if you can provide a GitHub or something like StackBlitz where I can easily reproduce the issue.

**Comment by phyzerbert** [comment]
I had removed (ionBlur), but i have to click 2 times to select item.
And i had tested (itemChange), but i can't fix the issue.
Would you please provide another solution?
