### ISSUE TITLE
Placing autocomplete insiide ion-chip

### ISSUE THREAD

**Issue by fguerzoni** [jrquick17/ionic4-auto-complete#7]
Hi,
thank you for the great component.
I would like to implement an 'Alibaba.com' like search bar with autocomplete.
I'm facing 2 problems I cannot solve by my own:
1) placing a working autocomplete inside an ion-chip it doesn't show suggestion list anymore. Debugging I can see it's able to run the getResults method but there could be a mismatch at DOM level.
2) I would like to hide the search icon and to shrink its space so to maximize usable space. But I'm not able to do so applying specific class in file complete-service.component.scss

Any advice?
BR
F

**Comment by jrquick17** [comment]
@fguerzoni Do you have repository or StackBlitz where I can reproduce the issue?

**Comment by fguerzoni** [comment]
Hi,
please have a look at:
https://github.com/fguerzoni/autocomplete-test
which is draft project to demo the requests.
Thanks and regards
F

**Comment by jrquick17** [comment]
Thanks for the example. The picker is working the ion-chip is just cutting off the suggestions. You can change the overflow on the `ion-chip` to see this.

Example:
```
<ion-chip color="primary" outline="true" style="overflow: visible;">
    <complete-service></complete-service>
    <ion-icon name="globe"></ion-icon>
</ion-chip>
```

You could also increase the height of the chip to see further:
```
<ion-chip color="primary" outline="true" style="height: 100px;">
    <complete-service></complete-service>
    <ion-icon name="globe"></ion-icon>
</ion-chip>
```
