### ISSUE TITLE
[Feature]:  support with floating label

### ISSUE THREAD

**Issue by msd117** [jrquick17/ionic4-auto-complete#71]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description

I wish it comes with the support for floating label

currently floating label is nor working because the ion item is getting a class name has a placeholder and also on focus the floating won't go up if I try to somehow manage the first part working
### Version Information

```
ionic4-auto-complete:2.7.2
@angular/cli: 9.1.7
@ionic:5.0.7
```

**Comment by jrquick17** [comment]
This feature has been added in [v2.8.0](https://github.com/jrquick17/ionic4-auto-complete/releases/tag/v2.8.0). 

It uses ion-label underneath which means to make the 'floating' position work you will have to enable ion-input. 

Example:
```
<ion-auto-complete [(model)]="selected"
                   [useIonInput]="true"
                   [label]="'Your Team'"
                   [labelPosition]="'floating'"></ion-auto-complete>
```
