### ISSUE TITLE
search bar placeholder doesn't work

### ISSUE THREAD

**Issue by winglovecola** [jrquick17/ionic4-auto-complete#72]
Hello,

I tried to change the text of the placeholder for the search bar but it doesn't work. Can you please look into this issue.

Thanks a lot!

**Comment by davidecampello** [comment]
same problem
Thanks

**Comment by jrquick17** [comment]
This [has been fixed](https://github.com/jrquick17/ionic4-auto-complete/commit/4be4ddfd093077b607d854405a3a4373b9bd64e5) and will be released in v2.8.2 today.
