### ISSUE TITLE
Making result on top of content if placed in the sidepane

### ISSUE THREAD

**Issue by lainard** [jrquick17/ionic4-auto-complete#73]
Hi

It works perfect on Ionic 5 but how do i add the result to be on top of the page if the component placed on side pane?

i tried z-index on ul class to -1 but does not work

 ul {
        position: absolute;
        width: 90vw;
        margin-top: 0;
        background: #FFF;
        list-style-type: none;
        padding: 0;
        left: 16px;
        z-index: -1;
......

}

Regards

**Comment by lainard** [comment]
https://ibb.co/qJ45LSn

example of issue

**Comment by jrquick17** [comment]
You can try setting `style="overflow: inherit;"` on the parent elements where ion-auto-complete exists. Take a look at [the demo's team picker tab](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/team-picker) for an example.

**Comment by lainard** [comment]
This does not help fix my issue
