### ISSUE TITLE
[BUG]: Not working on Ionic 5

### ISSUE THREAD

**Issue by blin4444** [jrquick17/ionic4-auto-complete#75]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

- [x] Bug: Description of the issue you encountered_
- [ ] Feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ionic4-auto-complete: 2.8.1
@angular/cli: 8.1.2
```

### Browser

- [x] Chrome - 84.0.4147.105
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

With Ionic 5, the list underneath the autocomplete search field is hidden. It seems that no matter what the z-index value is for the unordered list element, this is still the case.

![Screen Shot 2020-08-10 at 01 47 34](https://user-images.githubusercontent.com/2326556/89765998-42502480-daac-11ea-8920-eb6e7187e1ab.png)

**Comment by jrquick17** [comment]
Do you have more code to share? @blin4444

**Comment by jrquick17** [comment]
Please check the demo for examples of this working. There is a plan to release an update with updated Angular 10 and Ionic 5 versions which may help.

**Comment by dyegonery** [comment]
I'm also facing the same issue when using this component under the ion-header tag.
