### ISSUE TITLE
[BUG]: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by moritzvieli** [jrquick17/ionic4-auto-complete#77]
# I'm submitting a
Bug report

## Description
I am using Angular 8.2.14 and installed the latest version of ionic4-auto-complete. After importing the module, the following errors appear:
[ng]     ERROR in node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.d.ts(73,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.d.ts(74,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.d.ts(75,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.d.ts(76,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.d.ts(77,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.d.ts(78,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic4-auto-complete/auto-complete/auto-complete.component.d.ts(79,9): error TS1086: An accessor cannot be declared in an ambient context.

### Version Information
```
ionic4-auto-complete: 2.9.1
@angular/cli: 8.3.29
```

**Comment by gnowland** [comment]
Same here, if you want it to work on Angular 8 you have to downgrade to ionic4-auto-complete to version 2.8.x max.

**Comment by jrquick17** [comment]
This has been added to the documentation and changes to peer dependencies will come later to fix versioning.
