### ISSUE TITLE
SetValue is missing (removed as unused method)

### ISSUE THREAD

**Issue by WTimesTwo** [jrquick17/ionic4-auto-complete#78]
# I'm submitting a

- [ X ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Seems like setValue method was removed. It is widely used in our project, we have to freeze version on 2.9.0. Could you please provide reasoning/substitution for that? Our usecase is to set programmatically value of autocomplete component.

change was made in this commit https://github.com/jrquick17/ionic4-auto-complete/commit/ec81576b76e49e05569e0dd878e1047dcc8c5d3d

Thanks in advance for answer, best regards

- [ ] Bug: Description of the issue you encountered_
- [ ] Feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ionic4-auto-complete: 2.9.1
@angular/cli: 9.1.12
```

### Browser

- [ x ] Chrome - x.x.x
- [  x] Mozilla Firefox - x.x.x
- [ x ] Opera - x.x.x
- [ x ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by jrquick17** [comment]
My bad! This change has been reverted and will be released in v2.9.2 today.

**Comment by WTimesTwo** [comment]
Thanks 👍
