### ISSUE TITLE
I have to tap 2 times in order to select item

### ISSUE THREAD

**Issue by phyzerbert** [jrquick17/ionic4-auto-complete#81]
Hi, If i tap one item from the suggestions, the tapped item has a class "focus" but i can not catch (itemSelected) Event.
So i have to tap 2 times so that i can get itemSeleted event. Would you please let me know how to prevent this issue?
I will attach the screenshot.
![image](https://user-images.githubusercontent.com/46837938/100392216-28494a80-3079-11eb-8b89-aaca5578789e.png)
If i click Blue Dream, the item has a class "focus", but select event does not occur. How can i catch any event once click 1st time?
![image](https://user-images.githubusercontent.com/46837938/100392302-72cac700-3079-11eb-87d6-dad52297c2fa.png)
Or how to prevent the first click event?
Please let me know the solution, i am struggling to solve this issue for several months.
Thanks

**Comment by jrquick17** [comment]
Can you provide more details such as any/all of the following: which device, os version, browser, browser version, angular version, ionic version, and/or ionic4-auto-complete version?

**Comment by spasma** [comment]
I've experienced this issue as well. It's related to #59. My workaround is adding this following css to your global.scss file.

`
ion-autocomplete {
 ul li span {
  pointer-events: none;
 }
}
`

Somehow tapping on the span (the text) inside the autocomplete list is not always working.

**Comment by jrquick17** [comment]
Thanks for the report @phyzerbert and for the suggestion @spasma. I have included the solution in [this commit](https://github.com/jrquick17/ionic4-auto-complete/commit/f439201c44aedb304567eda1518686e3c0033a45) which will be released in v2.9.6 later today. Hopefully it helps!
