### ISSUE TITLE
Problem programmatically setting input value.

### ISSUE THREAD

**Issue by JonLevy** [jrquick17/ionic4-auto-complete#82]
BUG: programmatic setting of AutoCompleteComponent's value doesn't work

# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

There are two mechanisms for programmatically setting the input value that I think should work, but appear not to.

(1) The docs state that, "Ionic4-auto-complete supports the regular Ionic's Searchbar properties."[1].  This means there should be support for the `value` property supported by Ionic's Searchbar[2], as follows: `[options]="{value: anAttributeInScope}"`.  But this is not working to set the value.  (Nor is the similar `ngModel` attribute that works on Ion Searchbar (though it isn't specifically listed in the documentation).)

(2) `AutoCompleteComponent` extends `ControlValueAccessor` from `@angular/core`, which means that it should support the the `writeValue` method defined there[3].  However, attempting to access that method is not working either.

There is an ugly hack that seems to work by directly setting `formValue` and `keyword` of the `AutoCompleteComponent` element, but this feels like the wrong way to do it.

Btw, thank you for your work on this useful component!  And thank you, in advance, for your attention to this issue.

[1] https://www.npmjs.com/package/ionic4-auto-complete#searchbar-options
[2] https://ionicframework.com/docs/api/searchbar#properties
[3] https://angular.io/api/forms/ControlValueAccessor#writevalue

### Version Information

```
ionic4-auto-complete: 2.9.4
@angular/cli: 10.0.6
```

### Browser

- [x ] Chrome - 87.0.4280.67
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by jrquick17** [comment]
Thanks for the report @JonLevy. 

(1) The value passed in the options are now being respected as of v2.9.7, fixed [in this commit](https://github.com/jrquick17/ionic4-auto-complete/commit/dc40327144b815fbb1bd7d0a24f396e5e8882179). 

[ngModel] should work see [this comment](https://github.com/jrquick17/ionic4-auto-complete/issues/86#issuecomment-818074625) for more details.

(2) The write value method does exist, as you mentioned it is required for ControlValueAccessor.  Not sure why you cannot access it.  Feel free to share your code and I can look further.

If I am missing something please feel free to re-open this or another issue.
