### ISSUE TITLE
clearValue does not clear value

### ISSUE THREAD

**Issue by mediengestadler** [jrquick17/ionic4-auto-complete#83]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description
First. Nice plugin :-) Now to my problem. I tried to clear a value, after adding a skill. My code looks like following:

`<ion-auto-complete 
  (itemSelected)="addAutocompleteSkill($event)"
 ></ion-auto-complete>

@ViewChild(AutoCompleteComponent)
  autocomplete: AutoCompleteComponent;

public addAutocompleteSkill(): void {
    this.autocomplete.clearValue();
  }`

I get no errors and the value is, after calling the method, the same. Via options it was although not possible to clear the value. I found a way, but thats not compatible with lint, because the method which I use is private. 

` this.autocomplete.searchbarElem.nativeElement.value = '';`

Is there a way to clear the value, after adding?

### Version Information

```
ionic4-auto-complete: 2.8.1
@angular/cli: 9.1.5
```

### Browser

- [x ] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by jrquick17** [comment]
Thanks for the report. This has been included in v2.9.5. 

To clear the data just pass `null` or `[]` to `[(model)]`. [See this commit for an example.](https://github.com/jrquick17/ionic4-auto-complete/commit/d1c6cb265a09d8430987f87bbd2a83630135f050)
