### ISSUE TITLE
Option 'hideListOnSelection' has no effect

### ISSUE THREAD

**Issue by mgreg89** [jrquick17/ionic4-auto-complete#85]
Hello :)

Just encountered that the option 'hideListOnSelection' does not have any effect. That might be due to the following line:
https://github.com/jrquick17/ionic4-auto-complete/blob/f73a7c2d243c39eb60fd62a24122c412d5278388/src/auto-complete/auto-complete.component.ts#L733
which is called before 'hideListOnSelection' is in fact checked:
https://github.com/jrquick17/ionic4-auto-complete/blob/f73a7c2d243c39eb60fd62a24122c412d5278388/src/auto-complete/auto-complete.component.ts#L737-L739

**Comment by pankajparkar** [comment]
Facing the same issue, how to fix this? I want to enable multiselect option.

**Comment by mgreg89** [comment]
I just switched to use the option "alwaysShowList".

**Comment by jrquick17** [comment]
Thanks for reporting this issue. It has been resolved in this [commit](https://github.com/jrquick17/ionic4-auto-complete/commit/70e144d3e8eef0aaf1f0099e8806813c596bccf7) and will be released in v2.9.6 today.
