### ISSUE TITLE
the list is not shown if <ion-auto-complete> is inserted in an <ion-item>

### ISSUE THREAD

**Issue by VPantaleo** [jrquick17/ionic4-auto-complete#89]
Hi,

if I insert <ion-auto-complete> in a <ion-item>

The lists of values not show.

<ion-item>
    <ion-label position="floating">Località/Uso destinazione</ion-label>
    <ion-auto-complete class="ion-margin-top" [dataProvider]="this"></ion-auto-complete>
  </ion-item>

Please, help me

**Comment by jrquick17** [comment]
Please checkout the previous issue. 

https://github.com/jrquick17/ionic4-auto-complete/issues/28
