### ISSUE TITLE
[installation failed] ionic4-auto-complete - Angular 12 

### ISSUE THREAD

**Issue by GroupeBEL** [jrquick17/ionic4-auto-complete#90]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

- I'm trying to install ionic4-auto-complete in my project (ionic5/Angular 12) but it failed

### Version Information

```

ionic4-auto-complete: latest version

Ionic:

   Ionic CLI                     : 6.16.3
   Ionic Framework               : @ionic/angular 5.6.9
   @angular-devkit/build-angular : 12.0.3
   @angular-devkit/schematics    : 12.0.3
   @angular/cli                  : 12.0.3
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.11.1
   NodeJS            : v12.18.3
   npm               : 7.16.0
   OS                : macOS Big Sur
   Xcode             : Xcode 12.5 Build version 12E262

```

--> [log](https://drive.google.com/file/d/1zNQ82XBWcEY0MtLAc-OVD_V6bup9cf72/view?usp=sharing)

**Comment by jrquick17** [comment]
The project does work with 12 but has not been added to the peer dependencies yet. The latest version of NPM is more strict about dependency trees so in the meantime I would recommend installing with --force or rolling back your npm version.

**Comment by Eraldo** [comment]
I also ran into this when upgrading to angular 12.
```
 Could not resolve dependency:
npm WARN peer @angular/core@"^8.0.0 || 9.0.0 || ^10.0.0 || ^11.0.0" from ionic4-auto-complete@2.9.8
```

**Comment by jrquick17** [comment]
Suppoort for ng 12 has been added in v2.9.9
